from pydantic import BaseModel
from typing import Optional, List


class ReservationRequest(BaseModel):
    user_id: str                    # required — customer making the reservation
    product_id: str                 # required — SKU / product being reserved
    session_id: Optional[str] = None  # optional — for session continuity


class ReservationResponse(BaseModel):
    reservation_id: str             # e.g. "RES_A3FKP2QX"
    status: str                     # always "waiting" on creation
    qr_payload: str                 # same as reservation_id — used by QR scanner


class ChatRequest(BaseModel):
    message: str            # e.g. "Show me red kurtas under 2000 for Diwali"
    user_id: str            # e.g. "customer_001" — maps to customers.json
    session_id: Optional[str] = None


class Product(BaseModel):
    id: str
    name: str
    category: str
    subcategory: str
    gender_tags: List[str]
    price: float
    discounted_price: Optional[float] = None
    colors: List[str]           # array — matches products.json
    occasion_tags: List[str]    # from occasionTags in products.json
    sizes: List[str]
    online_stock: int           # from online_warehouse.quantity
    in_stock: bool
    image_url: str
    rating: float
    why_for_you: str = ""       # generated by recommendation agent
    availability_badge: Optional[str] = None


class ChatResponse(BaseModel):
    session_id: str
    intent: str                 # recommendation | inventory_check | loyalty_check | greeting | fallback
    message: str
    products: Optional[List[Product]] = []
    discount_info: Optional[str] = None
    metadata: Optional[dict] = None
    error: Optional[str] = None
